<div class="row">

    <div class="col-md-12">
        <nav aria-label="Pagination-Platzbelegung">
            <ul class="nav nav-tabs" id="court-select">
                <?php
                foreach ($courts as $court) {
                    ?>  
                <li id="court-selector-<?=$court->getId()?>"><a href='#' onclick='displayCourt(<?= $court->getId() ?>)'><?= $court->getName() ?></a></li>
                    <?php
                }
                ?>  
            </ul>
            <ul class="pagination navbar-right">
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url('home'); ?>?current_week=<?=$currentWeek - 1?>" aria-label="Zurück">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">zurück zur KW <?= ($currentWeek - 1) ?></span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link" href="#">KW <?= $currentWeek ?></a></li>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url('home'); ?>?current_week=<?=$currentWeek + 1?>" aria-label="Weiter">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">weiter zur KW <?= ($currentWeek + 1) ?></span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url('home'); ?>?current_week=<?=date('W')?>" aria-label="Aktuelle Woche" alt="Aktuelle Woche" title="Aktuelle WOche">
                        <span aria-hidden="true" class="glyphicon glyphicon-repeat"></span>
                        <span class="sr-only">aktuelle KW</span>
                    </a>
                </li>
            </ul>
        </nav>
        <?php
         foreach ($courts as $court) {
            ?>  
            <div id="court-<?= $court->getId() ?>" class="court-div">
                <h2><?= $court->getName() ?></h2>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col" class="col-md-1">Uhrzeit</th>
                            <?php
                            for ($weekDay = 0; $weekDay < 7; $weekDay++) {
                                ?>
                                <th scope="col" class="col-md-1"><?=
                                    $weekDays[$weekDay] . '<br>'
                                    . date('d.m.', strtotime($currentYear . 'W'.$currentWeek.' +' . $weekDay . 'days'))
                                    ?></th>
                                <?php
                            }
                            ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        for ($hour = 8; $hour <= 21; $hour++) {
                            ?>
                            <tr>
                                <th scope="row"><?= substr('00' . $hour, -2) ?>:00</th>
                                <?php
                                for ($weekDay = 0; $weekDay < 7; $weekDay++) {
                                    ?>
                                    <td onclick="alert(1);"><?= $court->getId() ?>-<?= $weekDay ?>-<?= $hour ?></td>
                                    <?php
                                }
                                ?>
                            </tr>
                            <?php
                        }
                        ?>

                    </tbody>
                </table>
            </div>

            <?php
        }
        ?>
    </div>

</div>
