<h1>Platzverwaltung</span></h1>
<div class="row">

    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Platzname</th>
                    <th>Aktion</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($courts as $court) {
                    ?>
                    <tr>
                        <td><?php echo $court->getName(); ?></td>
                        <td>                    
                            <a class="page-link" href="<?= $this->url('court'); ?>/edit/<?php echo $court->getId(); ?>" aria-label="Platz editieren" alt="Platz editieren" title="Platz editieren">
                                <span aria-hidden="true" class="glyphicon glyphicon-edit"></span>
                                <span class="sr-only">Platz editieren</span>
                            </a>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
    </div>
    <div class="col-md-12">
        <a class="btn btn-default" role="button" href="<?= $this->url('court'); ?>/edit/0" aria-label="Platz hinzufügen" alt="Platz hinzufügen" title="Platz hinzufügen">
            Platz hinzufügen
        </a>
    </div>
</div>
